[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino


monitor_speed = 115200
; Forza l'uso della PSRAM Quad SPI (R2)
board_build.arduino.memory_type = qio_qspi 
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 8MB

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=3  ; Ti aiuta a vedere errori nel terminale
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1    

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    robtillaart/MS5611 @ ^0.3.9
    greiman/SdFat @ ^2.2.2
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/AsyncTCP @ ^3.2.4
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    mprograms/QMC5883LCompass @ ^1.2.3
